//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organization.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Organization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роботрясы
        ///Бешеные огурцы
        ///Все в мясо
        ///Какие люди
        ///Каждому свое
        ///Без рубля
        ///Парад обезьян
        ///В мире животных
        ///Я люблю диван
        ///Люблю возить
        ///Тепленькая пошла
        ///Я все могу
        ///Денежный мешок
        ///Хомячки
        ///Нормальная компания
        ///Не слипнется
        ///Орден мяса и радуги
        ///Лечение одуванчиками
        ///Есть Никто
        ///Конец строительства
        ///Орда маков
        ///Невероятные усилия
        ///Операторы чистоты
        ///Бродячие музыканты
        ///Неадекватная мутация.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гусаров Карп Эрнестович
        ///Язьков Никанор Аникитевич
        ///Яницкий Феоктист Адамович
        ///Худяков Григорий Гордеевич
        ///Арцишевский Капитон Ипполитович
        ///Звягин Анатолий Сергеевич
        ///Модзалевский Тит Мечиславович
        ///Игнатов Варфоломей Серафимович
        ///Давыдов Самсон Семенович
        ///Глен Егор Михаилович
        ///Енютин Остап Леонидович
        ///Матвеев Петр Ипатович
        ///Завьялов Изяслав Куприянович
        ///Кярбер Сидор Тимурович
        ///Перевёртов Лавр Венедиктович
        ///Ловзанский Вадим Захарович
        ///Хренов Александр Брониславович
        ///Панюшкин Никифор Валериевич
        ///Якупов Гаврил [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
    }
}
